todo/config/routes.rb
Rails.application.routes.draw do

  resources :tasks

  root 'tasks#index'
end

todo/app/models/task.rb
class Task
	include Her::Model
	include_root_in_json true
end

todo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

todo/app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	before_action :set_task, only: [:show, :edit, :update ,:destroy]

	def index
		@tasks = Task.all
		respond_to do |format|
			format.html
		end
	end

	def show
		respond_to do |format|
			format.html
		end
	end

	def new
		@task = Task.new
		respond_to do |format|
			format.html
		end
	end

	def create
		@task = Task.new(task_params)

		respond_to do |format|
            if @task.save!
                format.html { redirect_to tasks_url, notice: 'Task was successfully created.' }
                format.json { render :show, status: :created, location: @task }
            else
                format.html { render :new }
                format.json { render json: @task.errors, status: :unprocessable_entity }
            end
        end
	end

	def edit
		# @task = Task.find(params[:id])
		respond_to do |format|
			format.html
		end
	end

	def update
		respond_to do |format|
			@task.attributes = params[:task]
            if @task.save
                format.html { redirect_to @task, notice: 'Task was successfully updated.' }
                format.json { render :show, status: :ok, location: @task }
            else
                format.html { render :edit }
                format.json { render json: @task.errors, status: :unprocessable_entity }
            end
        end
	end

	def destroy
		respond_to do |format|
	        if @task.destroy
	        	format.html { redirect_to tasks_url , notice: 'Task was successfully destroyed.' }
	        	format.json { render :index, status: :ok, location: @task }
	        end
        	# redirect_to tasks_url
        end
    end

    private

    def set_task
        @task = Task.find(params[:id])
    end

    def task_params
        params.require(:task).permit(:title, :body)
    end
end

todo/app/helpers/application_helper.rb
module ApplicationHelper
end

todo/app/helpers/tasks_helper.rb
module TasksHelper
end

todo/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

todo/app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'TODO App', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

todo/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

todo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><%= content_for?(:title) ? yield(:title) : "Todo Application" %></title>
        <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Todo" %>">
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <header>
            <%= render 'layouts/navigation' %>
        </header>
        <main role="main">
            <%= render 'layouts/messages' %>
            <div class="container">
                <%= yield %>
            </div>
        </main>
    </body>
</html>

todo/app/views/tasks/_task.html.erb
<table class="table table-hover">
	<thead>
    	<tr>
	    	<th>ID</th>
	    	<th>Title</th>
	    	<th>Options</th>
	     	<th colspan="3"></th>
    	</tr>
  	</thead>
  	<tbody>
		<%- @tasks.each do |task| -%>
			<tr>
				<td><%= task.id %></td>
				<td><%= link_to task.title, task %></td>
				<td><%= link_to "Edit", edit_task_path(task), :class => "btn btn-warning btn-xs" %>
				<%= link_to "Destroy", task_path(task), method: :delete,  data: { confirm: "You sure?" }, :class => "btn btn-danger btn-xs" %></td>
			</tr>
		<%- end -%>
	</tbody>
</table>

<br>

todo/app/views/tasks/edit.html.erb
<section class="content">
    <div class="span6 offset3">
        <%= form_for @task, :html => {'data-type' => 'json', :multipart => true, method: :put } do |f| %>
            <%#= render 'shared/error_messages', object: f.object %>
            <div class="row-4">
                <%= f.label :title %>
                <%= f.text_field :title %>
            </div>
            <br />
            <div class="row-4">
               <%= f.label :body, "Details" %>
                <%= f.text_area :body %>
            </div>
            <%= f.submit "Update", :class => "btn btn-success" %>
        <% end %>
    </div>
    <br />
    <div class="links">
        <%= link_to "Back", tasks_path %>
    </div>
</section>

todo/app/views/tasks/index.html.erb
<h3>Listing All Tasks</h3>

<ul class="tasks">
  <%= render "task" %>
</ul>

<%= link_to "New", new_task_path, :class => "btn btn-primary" %>

todo/app/views/tasks/new.html.erb
<section class="content">
    <div class="row">
        <div class="span6 offset3">
            <%= form_for @task, :html => {'data-type' => 'json', :multipart => true} do |f| %>
                <div class="row">
                    <%= f.label :title %>
                    <%= f.text_field :title %>
                </div>
                <br />
                <div class="row">
                   <%= f.label :body, "Details" %>
                    <%= f.text_area :body, cols: 20, rows: 5 %>
                </div>
                <%= f.submit "Create", :class => "btn btn-success" %>
            <% end %>
        </div>
    </div>
    <br />
    <div class="links">
        <%= link_to "Back", tasks_path %>
    </div>
</section>

todo/app/views/tasks/show.html.erb
<h3><%= @task.title %></h3>
<div>
	<%= @task.body %>
</div>

<br>

<%= link_to "Edit", edit_task_path, :class => "btn btn-warning btn-xs" %>
<%= link_to "Back", tasks_path, :class => "btn btn-primary btn-xs" %>